tracker/urls.py
from django.urls import path
from tracker import views


app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('continent_data/', views.chart, name='continent_data'),
    path('country/<slug:country_id_slug>/', views.country, name='country'),
    path('country_detail/<slug:country_id_slug>/', views.country_detail, name='country_detail'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('json_data/', views.json_data, name='json_data'),
    path('download/', views.download, name='file_download'),
    path('search/', views.search_bar, name='search'),
    path('mobile/', views.index_mobile, name='mobile_version'),
    path('mobile/country/<slug:country_id_slug>/', views.country_mobile, name='country_mobile_version'),
    path('map/',views.map,name = 'map'),
    path('location/',views.getGeoLocation,name='location')
]

tracking_board_project/urls.py
from django.contrib import admin
from django.urls import path, include

from tracker import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),

]

tracker/models.py
from django.db import models


class Country(models.Model):
    """
    Data table for country
    """
    country_name = models.CharField(max_length=128, blank=False)
    country_code = models.CharField(max_length=10, unique=True, primary_key=True)
    country_2digits_code = models.SlugField(max_length=3, default='ts')
    continent = models.CharField(max_length=128)
    population = models.DecimalField(blank=True, null=True, max_digits=20, decimal_places=0)
    population_density = models.DecimalField(max_digits=20, decimal_places=3)

    def save(self, *args, **kwargs):
        super(Country, self).save(*args, **kwargs)

    def __str__(self):
        return self.country_name


class Detail_Data_country(models.Model):
    """
    Data table for daily data
    """
    date = models.DateField(blank=False)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    cases = models.DecimalField(max_digits=20, decimal_places=0)
    total_cases = models.DecimalField(max_digits=20, decimal_places=0)
    cases_per_million = models.DecimalField(max_digits=20, decimal_places=3)
    total_cases_per_million = models.DecimalField(max_digits=20, decimal_places=3)
    deaths = models.DecimalField(max_digits=20, decimal_places=0)
    total_deaths = models.DecimalField(max_digits=20, decimal_places=0)
    deaths_per_million = models.DecimalField(max_digits=20, decimal_places=3)
    total_deaths_per_million = models.DecimalField(max_digits=20, decimal_places=3)
    modify_time = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        unique_together = ('date', 'country')

tracker/views.py
import datetime
import json
import os
import urllib.request

from django.db.models import Sum, F, Q
from django.http import JsonResponse, StreamingHttpResponse, HttpResponse
from django.shortcuts import render

from tracker.models import Country, Detail_Data_country
from tracking_board_project.settings import STATIC_DIR

_latest_date = Detail_Data_country.objects.all().values('date').order_by('-date')[:1]


def index(request):
    """
    Index page shows the home page that is constructed with three parts
    Overview: Global summary data
    Region View: View by Continent
    Table Data: View by Country

    """

    dataset = {}
    world = Country.objects.get(country_code='OWID_WRL')
    world_summary_data = Detail_Data_country.objects.filter(country=world).order_by('-date')[:1]

    query = Detail_Data_country.objects.exclude(country=world).filter(
        date=_latest_date[0]['date'])

    detail_data = query.order_by('-total_cases')
    continent_data = query.values('country__continent').annotate(total_cases=Sum('total_cases'),
                                                                 total_deaths=Sum('total_deaths'),
                                                                 cases=Sum('cases'),
                                                                 deaths=Sum('deaths')).order_by('-total_cases')

    dataset['WorldData'] = world_summary_data
    dataset['Detail'] = detail_data
    dataset['Continents'] = continent_data

    return render(request, 'tracker/index.html', context=dataset)


def json_data(request):
    """
    API for delivering the global and country data to the frontend

    """
    data = {}
    world_query = Detail_Data_country.objects.filter(country__country_code='OWID_WRL').order_by('date').values()
    q = Detail_Data_country.objects.exclude(country__country_code='OWID_WRL').filter(
        date=_latest_date[0]['date'])

    country_q = q.values('country__country_name', 'cases', 'deaths', 'total_cases', 'total_deaths',
                         'cases_per_million', 'total_cases_per_million', 'deaths_per_million',
                         'total_deaths_per_million').order_by('-total_cases')[:10]

    data['world_data'] = list(world_query)
    data['country_data'] = list(country_q)

    return JsonResponse(data)


def getGeoLocation(request):
    """
    Get the users'location via IP

    """
    data = {}
    req = urllib.request.Request('http://ip-api.com/json/', data=None)
    response = urllib.request.urlopen(req)
    if response.code == 200:
        encoding = response.headers.get_content_charset()
        data['location'] = json.loads(response.read().decode(encoding))

    return JsonResponse(data)


def map(request):
    """
    API for the map data
    """
    data = {}
    q = Detail_Data_country.objects.exclude(country__country_code='OWID_WRL').filter(
        date=_latest_date[0]['date'])
    map_query = q.annotate(code=F('country__country_2digits_code')).values()
    data['map_data'] = list(map_query)
    return JsonResponse(data)


def chart(request):
    """
    API for the graphs and charts
    """
    data = {}

    c = Detail_Data_country.objects.exclude(country__country_code='OWID_WRL')
    continent_query = c.values('date', 'country__continent').annotate(total_cases=Sum('total_cases'),
                                                                      total_deaths=Sum('total_deaths'),
                                                                      cases=Sum('cases'),
                                                                      deaths=Sum('deaths'))

    q = c.filter(date=_latest_date[0]['date'])
    pie_query = q.values('country__continent').annotate(total_cases=Sum('total_cases'),
                                                        total_deaths=Sum('total_deaths'),
                                                        cases=Sum('cases'),
                                                        deaths=Sum('deaths'))

    data['data_pie'] = list(pie_query)
    data['data_line'] = list(continent_query)
    return JsonResponse(data)


def country(request, country_id_slug):
    """
    Retrieve the country by country 2 digit code
    :param country_id_slug: 2 digit country code

    """
    data = {}
    query = Detail_Data_country.objects.filter(country_id__country_2digits_code=country_id_slug)
    data['Data'] = query
    data['LatestData'] = query.order_by('-date')[:1]
    data['country_id'] = Country.objects.get(country_2digits_code=country_id_slug)

    return render(request, 'tracker/country.html', context=data)


def country_detail(request, country_id_slug):
    """
    API to retrieve the country by country 2 digit code and process to the frontend
    :param country_id_slug: 2 digit country code

    """
    data = {}
    end_date = datetime.date.today()
    start_date = end_date - datetime.timedelta(days=300)
    query = Detail_Data_country.objects.filter(country_id__country_2digits_code=country_id_slug,
                                               date__range=(start_date, end_date)).order_by(
        'date')
    fields = query.values('country_id', 'date', 'cases', 'deaths', 'total_cases', 'total_deaths')
    data['data'] = list(fields)
    return JsonResponse(data)


def download(request):
    """
    Download the data to csv file from the website
    """
    def file_iterator(file_name, chunk_size=512):
        with open(file_name, 'rb') as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    file = os.path.join(STATIC_DIR, 'temp_files/detail.csv')
    response = StreamingHttpResponse(file_iterator(file))
    response['Content-Type'] = 'application/vnd.ms-excel'
    response['Content-Disposition'] = 'attachment;filename="data.csv"'
    return response


def search_bar(request):
    """
    Search by Country
    """
    query = Country.objects.get(country_name=request.GET.get('value')).country_2digits_code
    print(query)
    if query:
        return JsonResponse({'status': 'success', 'value': query})
    else:
        return JsonResponse({'status': 'failed'})


def autocomplete(request):
    """
    autocomplete function with search bar
    """
    response_data = {}
    input_data = request.GET.get('key')

    country_list = Country.objects.filter(Q(country_code__contains=input_data) | Q(country_name__contains=input_data))
    response_data['countryList'] = [Country.country_name for Country in country_list]

    return HttpResponse(json.dumps(response_data), content_type="application/json")


def index_mobile(request):
    """
    Mobile version: some elements have been simplified
    """
    dataset = {}

    world = Country.objects.get(country_code='OWID_WRL')
    world_summary_data = Detail_Data_country.objects.filter(country=world).order_by('-date')[:1]
    query = Detail_Data_country.objects.exclude(country=world).filter(
        date=_latest_date[0]['date'])

    detail_data = query.order_by('-total_cases')
    continent_data = query.values('country__continent').annotate(total_cases=Sum('total_cases'),
                                                                 total_deaths=Sum('total_deaths'),
                                                                 cases=Sum('cases'),
                                                                 deaths=Sum('deaths')).order_by('-total_cases')

    dataset['Detail'] = detail_data
    dataset['WorldData'] = world_summary_data
    dataset['Continents'] = continent_data

    return render(request, 'tracker/index_mobile.html', context=dataset)


def country_mobile(request, country_id_slug):
    """
    Mobile version
    """
    data = {}
    query = Detail_Data_country.objects.filter(country_id__country_2digits_code=country_id_slug)
    data['Data'] = query
    data['LatestData'] = query.order_by('-date')[:1]
    data['country_id'] = Country.objects.get(country_2digits_code=country_id_slug)

    return render(request, 'tracker/country_mobile.html', context=data)

templates/tracker/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>COVID-19 TRACKER</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="/static/css/nav.css">
  <link rel="stylesheet" href="/static/css/autocomplete.css">

  {% block header %}
  {% endblock %}
</head>

<body class="bg-light">
  {% block body_block %}
  {% endblock %}

    




    <!-- JavaScript -->
   
    <script src="/static/js/echarts.min.js"></script>
    <script src="/static/js/jquery(3.5.1).min.js"></script>
    <script src="/static/js/highcharts.js"></script>
    <script src="/static/js/map.js"></script>
  
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
      
    <script src="/static/js/jquery-ui.js"></script>


{% block footer %}
{% endblock %}

</body>

</html>

templates/tracker/country.html
{% extends 'tracker/base.html' %}
{% load static %}
{% load humanize %}
{% block body_block %}
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-1 px-3" href="/tracker/"> <img class="" style="width: 30px; height: 30px;" src="{% static 'images/logo.png' %}" > COVID-19 TRACKER</a>
    
        <input class="form-control form-control-dark w-100 autocomplete" id="search" type="text" placeholder="Search" data-url="{% url 'tracker:autocomplete'%}">
        <div class="dropdown">
        <button class="navbar-toggler" data-toggle="dropdown" id="navbarDropdown" aria-expanded="false"aria-haspopup="true">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    
          <a class="dropdown-item" href="/tracker/mobile/">Mobile Version</a>
        </div>
        </div>
      
    
      </nav>
    <div class="container">
        <div class=" pt-4 text-center">
            {% for data in LatestData %}
            <div class="col-md-4 text-left">

                <h1>{{data.country.country_name}}</h1>
                
                <p class="text-secondary">Data last updated :{{data.modify_time}}</p>
            </div>
            <div class="row pt-2">
                <div class="col-md-3">
                    <div class="card ">
                        <div class="card-body ">
                            <h4> {{data.cases|intcomma}}</h4>
                            <div class="card-text">New Cases</div>
                                                          
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4>{{data.deaths|intcomma}}</h4>
                            <div class="card-text">New Deaths</div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4>{{data.total_cases|intcomma}}</h4>
                            <div class="card-text">Total Cases</div>
                            
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h4>{{data.total_deaths|intcomma}}</h4>
                            <div class="card-text">Total Deaths</div>
                           
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="col-md-9">
                    <div class="row ">
                        <div id="main" class="col-md-6" style="height:300px;"></div>
                        <div id="new_case" class="col-md-6" style="height:300px;"></div>
                    </div>
                    <div class="row">
                        <div id="total_death" class="col-md-6" style="height:300px;"></div>
                        <div id="new_death" class="col-md-6" style="height:300px;"></div>
                    </div>
                </div>
            </div>
        </div>


    </div>
 {% endblock %}
    {% block footer%}
     <!-- script for detail charts -->
    <script type="text/javascript">

        var totalCaseChart = echarts.init(document.getElementById('main'));
        var newCaseChart = echarts.init(document.getElementById('new_case'));
        var totalDeathChart = echarts.init(document.getElementById('total_death'));
        var newDeathChart = echarts.init(document.getElementById('new_death'));

        // console.log(myChart)
        $.getJSON('/tracker/country_detail/{{country_id.country_2digits_code}}/', function (data) {
            var date = []
            var total_cases_value = []
            var new_case_value = []
            var total_deaths_value = []
            var new_death_value = []
            console.log(data)
            for (let index = 0; index < data.data.length; index++) {
                const element = data.data[index];
                date[index] = element.date;
                total_cases_value[index] = element.total_cases;
                new_case_value[index] = element.cases;
                total_deaths_value[index] = element.total_deaths;
                new_death_value[index] = element.deaths;

            }

            totalCaseChart.setOption({
                title: {
                    text: 'Total Cases',
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: ['Total Cases']
                },
                xAxis: {
                    type: 'category',
                    data: date
                },
                yAxis: [
                    {
                        type: 'value',
                        
                        axisLabel: {
                formatter: function (value, index) {
                  if (value >= 1000 && value < 1000000) {
                    value = value / 1000 + 'K';
                  } else if (value >= 1000000) {
                    value = value / 1000000 + 'M'
                  } else {
                    value = value;
                  }
                  return value
                }
              }
                    }
                ],
                series: [
                    {
                        name: 'Total Cases',
                        type: 'line',
                        smooth: true,
                        data: total_cases_value
                    }]
            })
            newCaseChart.setOption({
                title: {
                    text: 'New Case',
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: ['New Case']
                },
                xAxis: {
                    type: 'category',
                    data: date
                },
                yAxis: {
                    type: 'value',
                    name: 'new case',
                    axisLabel: {
                formatter: function (value, index) {
                  if (value >= 1000 && value < 1000000) {
                    value = value / 1000 + 'K';
                  } else if (value >= 1000000) {
                    value = value / 1000000 + 'M'
                  } else {
                    value = value;
                  }
                  return value
                }
              }
                },
                series: [
                    {
                        name: 'New Case',
                        type: 'bar',
                        data: new_case_value

                    }]
            })
            totalDeathChart.setOption({
                title: {
                    text: 'Total Deaths',
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: ['Total Deaths']
                },
                xAxis: {
                    type: 'category',
                    data: date
                },
                yAxis: [
                    {
                        type: 'value',
                        name: 'total deaths',
                        axisLabel: {
                formatter: function (value, index) {
                  if (value >= 1000 && value < 1000000) {
                    value = value / 1000 + 'K';
                  } else if (value >= 1000000) {
                    value = value / 1000000 + 'M'
                  } else {
                    value = value;
                  }
                  return value
                }
              }
                    }
                ],
                series: [
                    {
                        name: 'Total Deaths',
                        type: 'line',
                        smooth: true,
                        data: total_deaths_value
                    }]

            })
            newDeathChart.setOption({
                title: {
                    text: 'New Death',
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: ['New Death']
                },
                xAxis: {
                    type: 'category',
                    data: date
                },
                yAxis: {
                    type: 'value',
                    name: 'new death',
                    axisLabel: {
                formatter: function (value, index) {
                  if (value >= 1000 && value < 1000000) {
                    value = value / 1000 + 'K';
                  } else if (value >= 1000000) {
                    value = value / 1000000 + 'M'
                  } else {
                    value = value;
                  }
                  return value
                }
              }
                },
                series: [
                    {
                        name: 'New Death',
                        type: 'bar',
                        data: new_death_value

                    }]

            })

        }, 'json')
      //  console.log(myChart)


    </script>
 {% endblock %}

templates/tracker/index_mobile.html
{% extends 'tracker/base.html' %}
{% load static %}
{% load humanize %}

{% block body_block %}
    <nav class="navbar navbar-dark bg-dark sticky-top flex-md-nowrap p-0 shadow">
        <a class="navbar-brand mr-1 px-3" href="/tracker/"> <img class="" style="width: 30px; height: 30px;" src="{% static 'images/logo.png' %}" > COVID-19 TRACKER</a>
        <div class="dropdown">
        <button class="navbar-toggler" data-toggle="dropdown" id="navbarDropdown" aria-expanded="false"aria-haspopup="true"  data-target="#navbarsExample01" aria-controls="navbarsExample01"  >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <a class="dropdown-item" href="/tracker/">Desktop Version</a>
          </div>
        </div>
      </nav>

  <div class="container bg-white">

      
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
          aria-controls="nav-home" aria-selected="true">Overall view</a>
        <a class="nav-item nav-link" id="nav-continent-tab" data-toggle="tab" href="#nav-continent" role="tab"
          aria-controls="nav-continent" aria-selected="false">Regions View </a>
        <a class="nav-item nav-link" id="nav-country-tab" data-toggle="tab" href="#nav-country" role="tab"
          aria-controls="nav-country" aria-selected="false">Table Data</a>

      </div>
    </nav>
  

    <div class="tab-content" id="nav-tabContent">
      <!-- global data -->
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <!-- summary data -->
        {% for data in WorldData %}
        <div class="nav nav-tabs nav-fill" id="nav-data">
          

          <a class="nav-item nav-link active target" data-toggle="tab" href="#" id="cases" aria-label="New Cases">New
            Cases <h5>
              {{data.cases|intcomma}}</h5></a>
          <a class="nav-item nav-link target" data-toggle="tab" href="#" id="deaths" aria-label="New Deaths">New Deaths
            <h5>
              {{data.deaths|intcomma}}</h5></a>
          <a class="nav-item nav-link target" data-toggle="tab" href="#" id="total_cases" aria-label="Total Cases">Total
            Cases <h5>{{data.total_cases|intcomma}}</h5></a>
          <a class="nav-item nav-link target" data-toggle="tab" href="#" id="total_deaths"
            aria-label="Total Deaths">Total Deaths <h5>{{data.total_deaths|intcomma}}</h5></a>

          

        </div>



        <!-- Global Trends -->
        <div class="row pt-4">
          <div class="col-md-6 text-secondary">
          <div id='map'  style="height: 350px;">
            <div class="bg-light" style="background-color: #FFF2CC;">
              <!-- heat map -->
            </div>

          </div>
          <div class="card">
            <div class="card-body">
              <div class="row pl-3">        
                <svg class="mt-1 mr-1" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt " fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>             
                  <u><a class="text-secondary"  id="location" ></a></u> 
              </div>
              <div>Data last updated : {{data.modify_time}}</div> 
              <div>The data source is maily collected from ECDC, and the timely updated dataset of the virus infection can be <a class="text-secondary" href="{% url 'tracker:file_download'%}"><u> downloaded here.</u></a>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg" >
                  <path fill-rule="evenodd" d="M.5 8a.5.5 0 0 1 .5.5V12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.5a.5.5 0 0 1 1 0V12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8.5A.5.5 0 0 1 .5 8z"/>
                  <path fill-rule="evenodd" d="M5 7.5a.5.5 0 0 1 .707 0L8 9.793 10.293 7.5a.5.5 0 1 1 .707.707l-2.646 2.647a.5.5 0 0 1-.708 0L5 8.207A.5.5 0 0 1 5 7.5z"/>
                  <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0v-8A.5.5 0 0 1 8 1z"/>
                </svg></div>

            </div>
          </div>
        </div>
        {% endfor %}

          <div class="col-md-3" >
            <div id="new" style="height:250px;">test</div>
            <div id="total" style="height:250px;">test</div>
          </div>

        </div>

      </div>
      <!-- continent data -->
      <div class="tab-pane fade" id="nav-continent">
          <div class="col-md-3 ">
            {% for continent in Continents %}
            <div class="card" >
              <div class="card-body pb-3">
                <h6 class="card-title ">{{continent.country__continent}}</h6>
                <table  >
                  <tr>
                    <td>
                      <p class="card-text">Cases </p>
                    </td>
                    <td>
                      <h6 class="card-text">{{continent.total_cases|intcomma}}</h6>
                    </td>
                    <td>
                      <p class="card-text">+{{continent.cases|intcomma}}</p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <p class="card-text">Deaths</p>
                    </td>
                    <td>
                      <h6 class="card-text">{{continent.total_deaths|intcomma}}</h6>
                    </td>
                    <td>
                      <p class="card-text">+{{continent.deaths|intcomma}}</p>
                    </td>
                    
                  </tr>

                </table>
              </div>
            </div>
            {% endfor %}
          </div>

            <select class="custom-select " id="continent_select"> 
              <option value="cases">New Cases</option>
              <option value="deaths">New Deaths</option>
              <option value="total_cases">Total Cases</option>
              <option value="total_deaths">Total Deaths</option>
            </select>
            <div >
              <div id='chart'  style=" height: 250px"></div>

            <div id='continent_line_chart' style="height: 250px;"></div>
          </div>


      </div>
      <!-- country data -->
      <div class="tab-pane fade" id="nav-country" role="tabpanel" aria-labelledby="nav-country-tab">
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2 autocomplete"  id="search" type="text" placeholder="Search" data-url="{% url 'tracker:autocomplete'%}">
            <button class="btn btn-outline-success my-2 my-sm-0" id="searchButton" type="submit">Search</button>
          </form>
    

        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab">
            <table class="table ">
              <thead class="thead">
                <tr>
                  <th scope="col">Country</th>
                  <th scope="col">Total Cases</th>
                  <th scope="col">Total Deaths</th>


                </tr>
              </thead>
              <tbody>
                {% for data in Detail %}
                <tr>
                  <td><a href="country/{{data.country.country_2digits_code}}">{{data.country.country_name}}</a>
                  </td>
                  <td>{{data.total_cases|intcomma}}</td>
                  <td>{{data.total_deaths|intcomma}}</td>

                </tr>
                {% endfor %}
              </tbody>
            </table>
            </table>
          </div>
        </div>

      </div>
      <footer>
        
      </footer>
    </div>
  </div> 
    {% endblock %}

  {% block footer %}
     
<script src="/static/js/search_m.js"></script>

<script src="/static/js/mainpage_m.js"></script>

{% endblock %}